---
title: "results for age 14 SES measures sensitivity check"
output:
  word_document: default
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: console
---

libraries and custom functions

```{r}
library(mice)
library(pander)
library(xtable)
library(dplyr)
library(gt)
library(glue)
library(tidyverse)
library(flextable)
library(miceadds)
library(swfscMisc)
library(imputools)
library(haven)
library(sjmisc)
library(Hmisc)
library(psych)
library(lavaan)
library(gtools)

#this will take a float (e.g. a p value) and return a string with 3 digits and no leading 0

bv <- function(val) {
  return(sub("^(-?)0.", "\\1.", sprintf("%.2f", val)))
}

#if the number is less than .001, it will give <.001. 
pv1 <- function(val) {
  return(paste("=", sub("^(-?)0.", "\\1.", sprintf("%.3f", val))))
}



```


load in data 

```{r}
load("~/Documents/updated MCS datasets/inequalities datasets /2022-11-07_mcs-age14-sesVariables/2022-11-07_mcs-age14-sesVariables.Rdata")
imputed_mcs2 = mi.res
```

Regression models

```{r}
age14_nvq_unadjusted <- with(imputed_mcs2, lm(age14_standardised ~ highest_NVQ, weights = mcs2_weight))
age14_nvq_adjusted <- with(imputed_mcs2, lm(age14_standardised ~  gender +ethnicity +language_used_at_home +highest_NVQ, weights = mcs2_weight))
age14_income_unadjusted <- with(imputed_mcs2, lm(age14_standardised ~ income_quintiles, weights = mcs2_weight))
age14_income_adjusted <- with(imputed_mcs2, lm(age14_standardised ~ gender +ethnicity +language_used_at_home +income_quintiles, weights = mcs2_weight))
age14_wealth_unadjusted <- with(imputed_mcs2, lm(age14_standardised ~ wealth_quintiles, weights = mcs2_weight))
age14_wealth_adjusted <- with(imputed_mcs2, lm(age14_standardised ~  gender +ethnicity +language_used_at_home +wealth_quintiles, weights = mcs2_weight))
age14_occupation_unadjusted <- with(imputed_mcs2, lm(age14_standardised ~ occupational_status, weights = mcs2_weight))
age14_occupation_adjusted <- with(imputed_mcs2, lm(age14_standardised ~  gender +ethnicity +language_used_at_home+occupational_status, weights = mcs2_weight))
age14_imd_unadjusted <- with(imputed_mcs2, lm(age14_standardised ~ imd, weights = mcs2_weight))
age14_imd_adjusted <- with(imputed_mcs2, lm(age14_standardised ~  gender +ethnicity +language_used_at_home +imd, weights = mcs2_weight))

age14_confounders <- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home , weights = mcs2_weight))


#RESULTS
age14_nvq_results = round(summary(pool(age14_nvq_adjusted), conf.int =TRUE),2)
age14_income_results = round(summary(pool(age14_income_adjusted), conf.int =TRUE),2)
age14_wealth_results= round(summary(pool(age14_wealth_adjusted), conf.int =TRUE),2)
age14_occupation_results = round(summary(pool(age14_occupation_adjusted), conf.int =TRUE),2)
age14_imd_results = round(summary(pool(age14_imd_adjusted), conf.int =TRUE),2)


#pull out only SES predictor oefficients etc so dont have confounders
age14_nvq = age14_nvq_results[10:14, ]


age14_income = age14_income_results[10:13,]


age14_wealth = age14_wealth_results[10:13,]


age14_occupation = age14_occupation_results[10:12,]


age14_imd = age14_imd_results[10:18,]

age14_results = rbind(age14_nvq, age14_income, age14_wealth, age14_occupation, age14_imd)
```

Factor analysis to get composite ses predictor 

```{r}


imputed_mcs2_1 <- complete(imputed_mcs2,1)
imputed_mcs2_2 <- complete(imputed_mcs2,2)
imputed_mcs2_3 <- complete(imputed_mcs2,3)
imputed_mcs2_4 <- complete(imputed_mcs2,4)
imputed_mcs2_5 <- complete(imputed_mcs2,5)
imputed_mcs2_6 <- complete(imputed_mcs2,6)
imputed_mcs2_7 <- complete(imputed_mcs2,7)
imputed_mcs2_8 <- complete(imputed_mcs2,8)
imputed_mcs2_9 <- complete(imputed_mcs2,9)
imputed_mcs2_10 <- complete(imputed_mcs2,10)
imputed_mcs2_11 <- complete(imputed_mcs2,11)
imputed_mcs2_12 <- complete(imputed_mcs2,12)
imputed_mcs2_13 <- complete(imputed_mcs2,13)
imputed_mcs2_14 <- complete(imputed_mcs2,14)
imputed_mcs2_15 <- complete(imputed_mcs2,15)
imputed_mcs2_16 <- complete(imputed_mcs2,16)
imputed_mcs2_17 <- complete(imputed_mcs2,17)
imputed_mcs2_18 <- complete(imputed_mcs2,18)
imputed_mcs2_19 <- complete(imputed_mcs2,19)
imputed_mcs2_20<- complete(imputed_mcs2,20)
imputed_mcs2_21<- complete(imputed_mcs2,21)
imputed_mcs2_22<- complete(imputed_mcs2,22)
imputed_mcs2_23<- complete(imputed_mcs2,23)
imputed_mcs2_24<- complete(imputed_mcs2,24)
imputed_mcs2_25<- complete(imputed_mcs2,25)


#factor analysis to get factor score####
#factor analysis model


#create imputed datasets as a list - this is so can run CFA over each dataset
imputed_datasets = list(imputed_mcs2_1, imputed_mcs2_2, imputed_mcs2_3, imputed_mcs2_4, imputed_mcs2_5, 
                        imputed_mcs2_6, imputed_mcs2_7, imputed_mcs2_8, imputed_mcs2_9, imputed_mcs2_10, 
                        imputed_mcs2_11, imputed_mcs2_12, imputed_mcs2_13, imputed_mcs2_14, imputed_mcs2_15,
                        imputed_mcs2_16, imputed_mcs2_17, imputed_mcs2_18, imputed_mcs2_19, imputed_mcs2_20, 
                        imputed_mcs2_21, imputed_mcs2_22, imputed_mcs2_23, imputed_mcs2_24, imputed_mcs2_25)

#define CFA model to create SEP
SEP_model <- 'SEP=~ highest_NVQ + income_quintiles + wealth_quintiles + occupational_status + imd'

#run CFA across 25 imputed datasets
cfa_imputed = function(ert){
  fit = cfa(SEP_model, 
            data = ert,
            ordered = c("highest_NVQ", "income_quintiles","wealth_quintiles", "occupational_status", "imd"), 
            std.lv=TRUE, estimator="WLSMV")
  ses_latent = lavPredict(fit, type = "lv")
}

#create and add SES latent variable to each dataset
imputed_datasets$ses_latent = lapply(imputed_datasets, cfa_imputed)

#get individual datasets from list - these will now have SEP composite (pull this out for each dataset). 
#this is so can run the regression over each dataset. 
imputed_data1 = imputed_datasets[[1]]
imputed_data1$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[1]], center = TRUE, scale = TRUE))
#imputed_data1$ses_latent = scale(imputed_data1$ses_latent, center = TRUE, scale = TRUE)
imputed_data2 = imputed_datasets[[2]]
imputed_data2$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[2]], center = TRUE, scale = TRUE))
#imputed_data2$ses_latent = scale(imputed_data2$ses_latent, center = TRUE, scale = TRUE)
imputed_data3 = imputed_datasets[[3]]
imputed_data3$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[3]], center = TRUE, scale = TRUE))
#imputed_data3$ses_latent = scale(imputed_data3$ses_latent, center = TRUE, scale = TRUE)
imputed_data4 = imputed_datasets[[4]]
imputed_data4$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[4]], center = TRUE, scale = TRUE))
#imputed_data4$ses_latent = scale(imputed_data4$ses_latent, center = TRUE, scale = TRUE)
imputed_data5 = imputed_datasets[[5]]
imputed_data5$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[5]], center = TRUE, scale = TRUE))
#imputed_data5$ses_latent = scale(imputed_data5$ses_latent, center = TRUE, scale = TRUE)
imputed_data6 = imputed_datasets[[6]]
imputed_data6$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[6]], center = TRUE, scale = TRUE))
#imputed_data6$ses_latent = scale(imputed_data6$ses_latent, center = TRUE, scale = TRUE)
imputed_data7 = imputed_datasets[[7]]
imputed_data7$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[7]], center = TRUE, scale = TRUE))
#imputed_data7$ses_latent = scale(imputed_data7$ses_latent, center = TRUE, scale = TRUE)
imputed_data8 = imputed_datasets[[8]]
imputed_data8$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[8]], center = TRUE, scale = TRUE))
#imputed_data8$ses_latent = scale(imputed_data8$ses_latent, center = TRUE, scale = TRUE)
imputed_data9 = imputed_datasets[[9]]
imputed_data9$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[9]], center = TRUE, scale = TRUE))
#imputed_data9$ses_latent = scale(imputed_data9$ses_latent, center = TRUE, scale = TRUE)
imputed_data10 = imputed_datasets[[10]]
imputed_data10$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[10]], center = TRUE, scale = TRUE))
#imputed_data10$ses_latent = scale(imputed_data10$ses_latent, center = TRUE, scale = TRUE)
imputed_data11 = imputed_datasets[[11]]
imputed_data11$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[11]],center = TRUE, scale = TRUE))
#imputed_data11$ses_latent = scale(imputed_data11$ses_latent, center = TRUE, scale = TRUE)
imputed_data12 = imputed_datasets[[12]]
imputed_data12$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[12]], center = TRUE, scale = TRUE))
#imputed_data12$ses_latent = scale(imputed_data12$ses_latent, center = TRUE, scale = TRUE)
imputed_data13 = imputed_datasets[[13]]
imputed_data13$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[13]], center = TRUE, scale = TRUE))
#imputed_data13$ses_latent = scale(imputed_data13$ses_latent, center = TRUE, scale = TRUE)
imputed_data14 = imputed_datasets[[14]]
imputed_data14$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[14]], center = TRUE, scale = TRUE))
#imputed_data14$ses_latent = scale(imputed_data14$ses_latent, center = TRUE, scale = TRUE)
imputed_data15 = imputed_datasets[[15]]
imputed_data15$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[15]], center = TRUE, scale = TRUE))
#imputed_data15$ses_latent = scale(imputed_data15$ses_latent, center = TRUE, scale = TRUE)
imputed_data16 = imputed_datasets[[16]]
imputed_data16$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[16]], center = TRUE, scale = TRUE))
#imputed_data16$ses_latent = scale(imputed_data16$ses_latent, center = TRUE, scale = TRUE)
imputed_data17 = imputed_datasets[[17]]
imputed_data17$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[17]], center = TRUE, scale = TRUE))
#imputed_data17$ses_latent = scale(imputed_data17$ses_latent, center = TRUE, scale = TRUE)
imputed_data18 = imputed_datasets[[18]]
imputed_data18$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[18]], center = TRUE, scale = TRUE))
#imputed_data18$ses_latent = scale(imputed_data18$ses_latent, center = TRUE, scale = TRUE)
imputed_data19 = imputed_datasets[[19]]
imputed_data19$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[19]], center = TRUE, scale = TRUE))
#imputed_data19$ses_latent = scale(imputed_data19$ses_latent, center = TRUE, scale = TRUE)
imputed_data20 = imputed_datasets[[20]]
imputed_data20$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[20]], center = TRUE, scale = TRUE))
#imputed_data20$ses_latent = scale(imputed_data20$ses_latent, center = TRUE, scale = TRUE)
imputed_data21 = imputed_datasets[[21]]
imputed_data21$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[21]], center = TRUE, scale = TRUE))
#imputed_data21$ses_latent = scale(imputed_data21$ses_latent, center = TRUE, scale = TRUE)
imputed_data22 = imputed_datasets[[22]]
imputed_data22$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[22]], center = TRUE, scale = TRUE))
#imputed_data22$ses_latent = scale(imputed_data22$ses_latent, center = TRUE, scale = TRUE)
imputed_data23 = imputed_datasets[[23]]
imputed_data23$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[23]], center = TRUE, scale = TRUE))
#imputed_data23$ses_latent = scale(imputed_data23$ses_latent, center = TRUE, scale = TRUE)
imputed_data24 = imputed_datasets[[24]]
imputed_data24$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[24]], center = TRUE, scale = TRUE))
#imputed_data24$ses_latent = scale(imputed_data24$ses_latent, center = TRUE, scale = TRUE)
imputed_data25 = imputed_datasets[[25]]
imputed_data25$ses_latent = as.numeric(scale(imputed_datasets$ses_latent[[25]], center = TRUE, scale = TRUE))
#imputed_data25$ses_latent = scale(imputed_data25$ses_latent, center = TRUE, scale = TRUE)

#create composite SEC quintiles (these will be used for plotting later)
#add composite quintiles to data
#data 1
imputed_data1$composite_quintiles = quantcut(imputed_data1$ses_latent,5)
levels(imputed_data1$composite_quintiles)[1] = "1"
levels(imputed_data1$composite_quintiles)[2] = "2"
levels(imputed_data1$composite_quintiles)[3] = "3"
levels(imputed_data1$composite_quintiles)[4] = "4"
levels(imputed_data1$composite_quintiles)[5] = "5"
#data2
imputed_data2$composite_quintiles = quantcut(imputed_data2$ses_latent,5)
levels(imputed_data2$composite_quintiles)[1] = "1"
levels(imputed_data2$composite_quintiles)[2] = "2"
levels(imputed_data2$composite_quintiles)[3] = "3"
levels(imputed_data2$composite_quintiles)[4] = "4"
levels(imputed_data2$composite_quintiles)[5] = "5"
#data3
imputed_data3$composite_quintiles = quantcut(imputed_data3$ses_latent,5)
levels(imputed_data3$composite_quintiles)[1] = "1"
levels(imputed_data3$composite_quintiles)[2] = "2"
levels(imputed_data3$composite_quintiles)[3] = "3"
levels(imputed_data3$composite_quintiles)[4] = "4"
levels(imputed_data3$composite_quintiles)[5] = "5"
#dat4
imputed_data4$composite_quintiles = quantcut(imputed_data4$ses_latent,5)
levels(imputed_data4$composite_quintiles)[1] = "1"
levels(imputed_data4$composite_quintiles)[2] = "2"
levels(imputed_data4$composite_quintiles)[3] = "3"
levels(imputed_data4$composite_quintiles)[4] = "4"
levels(imputed_data4$composite_quintiles)[5] = "5"
#DATA5
imputed_data5$composite_quintiles = quantcut(imputed_data5$ses_latent,5)
levels(imputed_data5$composite_quintiles)[1] = "1"
levels(imputed_data5$composite_quintiles)[2] = "2"
levels(imputed_data5$composite_quintiles)[3] = "3"
levels(imputed_data5$composite_quintiles)[4] = "4"
levels(imputed_data5$composite_quintiles)[5] = "5"
#data6
imputed_data6$composite_quintiles = quantcut(imputed_data6$ses_latent,5)
levels(imputed_data6$composite_quintiles)[1] = "1"
levels(imputed_data6$composite_quintiles)[2] = "2"
levels(imputed_data6$composite_quintiles)[3] = "3"
levels(imputed_data6$composite_quintiles)[4] = "4"
levels(imputed_data6$composite_quintiles)[5] = "5"
#data7
imputed_data7$composite_quintiles = quantcut(imputed_data7$ses_latent,5)
levels(imputed_data7$composite_quintiles)[1] = "1"
levels(imputed_data7$composite_quintiles)[2] = "2"
levels(imputed_data7$composite_quintiles)[3] = "3"
levels(imputed_data7$composite_quintiles)[4] = "4"
levels(imputed_data7$composite_quintiles)[5] = "5"
#data 8
imputed_data8$composite_quintiles = quantcut(imputed_data8$ses_latent,5)
levels(imputed_data8$composite_quintiles)[1] = "1"
levels(imputed_data8$composite_quintiles)[2] = "2"
levels(imputed_data8$composite_quintiles)[3] = "3"
levels(imputed_data8$composite_quintiles)[4] = "4"
levels(imputed_data8$composite_quintiles)[5] = "5"
#data 9 
imputed_data9$composite_quintiles = quantcut(imputed_data9$ses_latent,5)
levels(imputed_data9$composite_quintiles)[1] = "1"
levels(imputed_data9$composite_quintiles)[2] = "2"
levels(imputed_data9$composite_quintiles)[3] = "3"
levels(imputed_data9$composite_quintiles)[4] = "4"
levels(imputed_data9$composite_quintiles)[5] = "5"
#data10
imputed_data10$composite_quintiles = quantcut(imputed_data10$ses_latent,5)
levels(imputed_data10$composite_quintiles)[1] = "1"
levels(imputed_data10$composite_quintiles)[2] = "2"
levels(imputed_data10$composite_quintiles)[3] = "3"
levels(imputed_data10$composite_quintiles)[4] = "4"
levels(imputed_data10$composite_quintiles)[5] = "5"
#data11
imputed_data11$composite_quintiles = quantcut(imputed_data11$ses_latent,5)
levels(imputed_data11$composite_quintiles)[1] = "1"
levels(imputed_data11$composite_quintiles)[2] = "2"
levels(imputed_data11$composite_quintiles)[3] = "3"
levels(imputed_data11$composite_quintiles)[4] = "4"
levels(imputed_data11$composite_quintiles)[5] = "5"
#data12
imputed_data12$composite_quintiles = quantcut(imputed_data12$ses_latent,5)
levels(imputed_data12$composite_quintiles)[1] = "1"
levels(imputed_data12$composite_quintiles)[2] = "2"
levels(imputed_data12$composite_quintiles)[3] = "3"
levels(imputed_data12$composite_quintiles)[4] = "4"
levels(imputed_data12$composite_quintiles)[5] = "5"
#data13
imputed_data13$composite_quintiles = quantcut(imputed_data13$ses_latent,5)
levels(imputed_data13$composite_quintiles)[1] = "1"
levels(imputed_data13$composite_quintiles)[2] = "2"
levels(imputed_data13$composite_quintiles)[3] = "3"
levels(imputed_data13$composite_quintiles)[4] = "4"
levels(imputed_data13$composite_quintiles)[5] = "5"
#data14
imputed_data14$composite_quintiles = quantcut(imputed_data14$ses_latent,5)
levels(imputed_data14$composite_quintiles)[1] = "1"
levels(imputed_data14$composite_quintiles)[2] = "2"
levels(imputed_data14$composite_quintiles)[3] = "3"
levels(imputed_data14$composite_quintiles)[4] = "4"
levels(imputed_data14$composite_quintiles)[5] = "5"
#data15
imputed_data15$composite_quintiles = quantcut(imputed_data15$ses_latent,5)
levels(imputed_data15$composite_quintiles)[1] = "1"
levels(imputed_data15$composite_quintiles)[2] = "2"
levels(imputed_data15$composite_quintiles)[3] = "3"
levels(imputed_data15$composite_quintiles)[4] = "4"
levels(imputed_data15$composite_quintiles)[5] = "5"
#data16
imputed_data16$composite_quintiles = quantcut(imputed_data16$ses_latent,5)
levels(imputed_data16$composite_quintiles)[1] = "1"
levels(imputed_data16$composite_quintiles)[2] = "2"
levels(imputed_data16$composite_quintiles)[3] = "3"
levels(imputed_data16$composite_quintiles)[4] = "4"
levels(imputed_data16$composite_quintiles)[5] = "5"
#data 17
imputed_data17$composite_quintiles = quantcut(imputed_data17$ses_latent,5)
levels(imputed_data17$composite_quintiles)[1] = "1"
levels(imputed_data17$composite_quintiles)[2] = "2"
levels(imputed_data17$composite_quintiles)[3] = "3"
levels(imputed_data17$composite_quintiles)[4] = "4"
levels(imputed_data17$composite_quintiles)[5] = "5"
#data18
imputed_data18$composite_quintiles = quantcut(imputed_data18$ses_latent,5)
levels(imputed_data18$composite_quintiles)[1] = "1"
levels(imputed_data18$composite_quintiles)[2] = "2"
levels(imputed_data18$composite_quintiles)[3] = "3"
levels(imputed_data18$composite_quintiles)[4] = "4"
levels(imputed_data18$composite_quintiles)[5] = "5"
#data 19
imputed_data19$composite_quintiles = quantcut(imputed_data19$ses_latent,5)
levels(imputed_data19$composite_quintiles)[1] = "1"
levels(imputed_data19$composite_quintiles)[2] = "2"
levels(imputed_data19$composite_quintiles)[3] = "3"
levels(imputed_data19$composite_quintiles)[4] = "4"
levels(imputed_data19$composite_quintiles)[5] = "5"
#data 20
imputed_data20$composite_quintiles = quantcut(imputed_data20$ses_latent,5)
levels(imputed_data20$composite_quintiles)[1] = "1"
levels(imputed_data20$composite_quintiles)[2] = "2"
levels(imputed_data20$composite_quintiles)[3] = "3"
levels(imputed_data20$composite_quintiles)[4] = "4"
levels(imputed_data20$composite_quintiles)[5] = "5"
#data 21
imputed_data21$composite_quintiles = quantcut(imputed_data21$ses_latent,5)
levels(imputed_data21$composite_quintiles)[1] = "1"
levels(imputed_data21$composite_quintiles)[2] = "2"
levels(imputed_data21$composite_quintiles)[3] = "3"
levels(imputed_data21$composite_quintiles)[4] = "4"
levels(imputed_data21$composite_quintiles)[5] = "5"
#data22
imputed_data22$composite_quintiles = quantcut(imputed_data22$ses_latent,5)
levels(imputed_data22$composite_quintiles)[1] = "1"
levels(imputed_data22$composite_quintiles)[2] = "2"
levels(imputed_data22$composite_quintiles)[3] = "3"
levels(imputed_data22$composite_quintiles)[4] = "4"
levels(imputed_data22$composite_quintiles)[5] = "5"
#data 23
imputed_data23$composite_quintiles = quantcut(imputed_data23$ses_latent,5)
levels(imputed_data23$composite_quintiles)[1] = "1"
levels(imputed_data23$composite_quintiles)[2] = "2"
levels(imputed_data23$composite_quintiles)[3] = "3"
levels(imputed_data23$composite_quintiles)[4] = "4"
levels(imputed_data23$composite_quintiles)[5] = "5"
#data 24
imputed_data24$composite_quintiles = quantcut(imputed_data24$ses_latent,5)
levels(imputed_data24$composite_quintiles)[1] = "1"
levels(imputed_data24$composite_quintiles)[2] = "2"
levels(imputed_data24$composite_quintiles)[3] = "3"
levels(imputed_data24$composite_quintiles)[4] = "4"
levels(imputed_data24$composite_quintiles)[5] = "5"
#data 25
imputed_data25$composite_quintiles = quantcut(imputed_data25$ses_latent,5)
levels(imputed_data25$composite_quintiles)[1] = "1"
levels(imputed_data25$composite_quintiles)[2] = "2"
levels(imputed_data25$composite_quintiles)[3] = "3"
levels(imputed_data25$composite_quintiles)[4] = "4"
levels(imputed_data25$composite_quintiles)[5] = "5"

#age 14 OUTCOME REGRESSION MODELS####
# age 14 imputed dataset  1 regression model 

age14_model <- function(df) {
  fit <- lm(age14_standardised ~ gender +ethnicity + language_used_at_home + ses_latent, 
            weight= mcs2_weight, data=df)
  return(fit)
}

#regression model to list of imputed datasets
age14CompositeResults <- lapply(list(imputed_data1, imputed_data2, imputed_data3, imputed_data4, imputed_data5,
                                    imputed_data6, imputed_data7, imputed_data8, imputed_data9, imputed_data10,
                                    imputed_data11, imputed_data12, imputed_data13, imputed_data14, imputed_data15,
                                    imputed_data16, imputed_data17, imputed_data18, imputed_data19, imputed_data20,
                                    imputed_data21, imputed_data22, imputed_data23, imputed_data24, imputed_data25),
                               age14_model)
#results
age14_latentResults <- summary(pool(as.mira(age14CompositeResults)),conf.int = TRUE, conf.level = 0.95) 

#confounders only 
age14_compositeConfounders <- function(df) {
  fit <- lm(age14_standardised ~ gender + ethnicity + language_used_at_home, weight=mcs2_weight, data=df)
  return(fit)
}

age14CompositeConfoundersResults <- lapply(list(imputed_data1, imputed_data2, imputed_data3, imputed_data4, imputed_data5,
                                  imputed_data6, imputed_data7, imputed_data8, imputed_data9, imputed_data10,
                                  imputed_data11, imputed_data12, imputed_data13, imputed_data14, imputed_data15,
                                  imputed_data16, imputed_data17, imputed_data18, imputed_data19, imputed_data20,
                                  imputed_data21, imputed_data22, imputed_data23, imputed_data24, imputed_data25),
                             age14_compositeConfounders)


age14_latent_results <- age14_latentResults[10,]
age14_latent_results$`2.5 %` = bv(age14_latent_results$`2.5 %`)
age14_latent_results$`97.5 %` = bv(age14_latent_results$`97.5 %`)
age14_latent_results$CIs = paste0("[", age14_latent_results$`2.5 %`, ";", age14_latent_results$`97.5 %`, "]")

```


#start to gather relevant information for tables

```{r}
age14_results$estimate = bv(age14_results$estimate) #no leading 0 
#age14_results$estimate = round(age14_results$estimate,2)
age14_results$`2.5 %` = bv(age14_results$`2.5 %`)
age14_results$`97.5 %` = bv(age14_results$`97.5 %`)
age14_results$p.value1= ifelse(age14_results$p.value< .001, "<.001" , pv1(age14_results$p.value))
#age14_results$p.value = round(age14_results$p.value, 3)
age14_results$coefficient = paste0(age14_results$estimate, "[", age14_results$`2.5 %`, ";", age14_results$`97.5 %`, "]")
#age14_results$p.value [age14_results$p.value <.001] <- paste0("<.001") #change p=0.000 to p<.001
age14_results$stars = add.significance.stars(age14_results$p.value, cutoffs=c(0.05, 0.01, 0.001))
age14_results$p1 = paste0(age14_results$p.value1, "") 
age14_results$p = paste0("p", age14_results$p1)
age14_results$new_coef = paste0(age14_results$coefficient, age14_results$stars)#combine coefficients and stars into column.


age14_latent_results$estimate = bv(age14_latent_results$estimate) #no leading 0 
age14_latent_results$p.value1= ifelse(age14_latent_results$p.value< .001, "<.001" , pv1(age14_latent_results$p.value))
#age14_latent_results$p.value = round(age14_latent_results$p.value, 3)
age14_latent_results$coefficient = paste0(age14_latent_results$estimate, age14_latent_results$CIs)
#age14_latent_results$p.value [age14_latent_results$p.value <.001] <- paste0("<.001") #change p=0.000 to p<.001
age14_latent_results$stars = add.significance.stars(age14_latent_results$p.value, cutoffs=c(0.05, 0.01, 0.001))
age14_latent_results$p1 = paste0(age14_latent_results$p.value1, "")
age14_latent_results$p = paste0("p", age14_latent_results$p1)
age14_latent_results$new_coef = paste0(age14_latent_results$coefficient, age14_latent_results$stars)  #combine coefficients and stars into column.
age14_composite_result <- age14_latent_results %>% 
  select(term, new_coef, p)

age14_tableData <- age14_results %>%  select(term, new_coef, p)
age14_tableData= as_tibble(age14_tableData)


age14_tableData = rbind(age14_tableData, age14_composite_result)

#write results how would want them in results table (all in one column)
age14_tableData$age14 <- paste0(age14_tableData$new_coef,"\n", age14_tableData$p)

age14_tableData <- age14_tableData%>% 
  select(term, age14)

names(age14_tableData) <- c("Indicator", "age14")

#add in reference categories 
ses_table_data= age14_tableData %>% add_row(Indicator= "highest_NVQ1",  .before=1) %>% 
  add_row(Indicator= "income_quintiles1",  .before=7) %>% 
  add_row(Indicator= "wealth_quintiles1",  .before=12) %>% 
  add_row(Indicator= "occupational_status2",  .before=17) %>% 
  add_row(Indicator= "imd1",  .before=21)  
ses_table_data[is.na(ses_table_data)] <- "REFERENCE"

#add indicator labels for vertical column in table. space for most of these as will merge cells later. 
ses_table_data = ses_table_data %>%  add_column(z= c("Parent Education", "  ", "  ", "  ", "  ", "  ",
                                                     "Income", "  ", "  ", "  ", "  ",  
                                                     "Wealth",  "  ", "  ", "  ", "  ", 
                                                     "Occupational Status",  "  ", "  ", "  ",
                                                     "Neighbourhood Deprivation",  "  ", "  ", "  ", "  ",  "  ", "  ", "  ", "  ",  "  ", "Composite"),.before = 1)

#rename SES variables
ses_table_data$Indicator <- c("Parent Education \n (NVQ1)", "Parent Education \n (None of these/overseas qualifications)", "Parent Education \n (NVQ2", "Parent Education \n (NVQ3)", "Parent Education \n (NVQ4)", "Parent Education \n (NVQ5)", 
                           "Income Quintile 1", "Income Quintile", "Income Quintile 3", "Income Quintile 4", "Income Quintile 5", 
                          "Wealth Quintile 1", "Wealth Quintile 2", "Wealth Quintile 3", "Wealth Quintile 4", "Wealth Quintile 5", "Occupational Status \n (routine)", "Occupational Status \n (unemployed)", "Occupational Status \n (intermediate)", "Occupational Status \n (higher managerial)",  "Relative Neighbourhood \n Deprivation \n (most deprived decile)", "Relative Neighbourhood \n Deprivation \n (10 - <20%)", "Relative Neighbourhood \n Deprivation \n (20 - <30%)", "Relative Neighbourhood \n Deprivation \n (30 - <40%)", "Relative Neighbourhood \n Deprivation \n (40 - <50%)", "Relative Neighbourhood \n Deprivation \n (50 - <60%)", "Relative Neighbourhood \n Deprivation \n (60 - <70%)", "Relative Neighbourhood \n  Deprivation \n (70 - <80%)", "Relative Neighbourhood \n Deprivation \n (80 - <90%)", "Relative Neighbourhood \n Deprivation \n (least deprived decile)", "Composite SEP")

ses_table_data[is.na(ses_table_data)] <- "   "
```

Make table using flextable package 
```{r}
library(officer)

#define border
my_border = border= fp_border(color="black", width=1)
ses_table_flex <- ses_table_data %>% 
  flextable() %>% 
  font(fontname = "Times New Roman", part="all") %>% 
  fontsize(size=11, part = "all") %>% 
  align(j=2, align="left", part="all") %>% 
  align(j=3, align="center", part="all") %>% 
  color(j=1:3, color="black", part="all") %>% 
  width(j=1, width=0.5) %>% 
  width(j=2, width=1.5) %>% 
  width(j=3, width=1.3) %>% 
  line_spacing(j=3, space=1.5) %>% 
  line_spacing(j=1, space=1.5) %>% 
  border_remove() %>% 
  hline_top(j=1:3, part="all", border=my_border) %>% 
  hline_bottom(j=1:3,part="body",  border=my_border) %>% 
  set_header_labels(z= " ", Inidcator= "Indicator", "Age 14") %>% 
  merge_at(j=1, i = 1:6) %>% 
  merge_at(j=1, i=7:11) %>% 
  merge_at(j=1, i = 12:16) %>%
  merge_at(j=1, i = 17:20) %>% 
  merge_at(j=1, i=21:30) %>% 
  rotate(i=1:6, j=1, rotation="btlr", align="center") %>% 
  rotate(i=7:11, j=1, rotation="btlr", align="center") %>% 
  rotate(i=12:16, j=1, rotation="btlr", align="center") %>% 
  rotate(i=17:20, j=1, rotation="btlr", align="center") %>% 
  rotate(i=21:30, j=1, rotation="btlr", align="center") %>% 
  rotate(i=31, j=1, rotation="btlr", align="center") %>% 
  align(j=1, align="center", part="all") %>% 
  
  
  
 print( preview = "docx") 

```


#now the r squared table!

```{r}
age14_ed_r2 = round(pool.r.squared(age14_nvq_adjusted),4)*100
age14_income_r2 = round(pool.r.squared(age14_income_adjusted),4)*100
age14_wealth_r2= round(pool.r.squared(age14_wealth_adjusted),4)*100
age14_occupation_r2 = round(pool.r.squared(age14_occupation_adjusted),4)*100
age14_imd_r2 = round(pool.r.squared(age14_imd_adjusted),4)*100
age14_confounders_r2 = round(pool.r.squared(age14_confounders),4)*100
#partial r squareds
age14_ed_partial = age14_ed_r2 - age14_confounders_r2
age14_income_partial = age14_income_r2 - age14_confounders_r2
age14_wealth_partial = age14_wealth_r2 - age14_confounders_r2
age14_occupation_partial = age14_occupation_r2 - age14_confounders_r2
age14_imd_partial = age14_imd_r2 - age14_confounders_r2

age14_composite_r2 <- as.data.frame(pool.r.squared(as.mira(age14CompositeResults)))*100
#confounders only
age14_composite_confounders_r2 <- as.data.frame(pool.r.squared(as.mira(age14CompositeConfoundersResults)))*100
age14_composite_partial <- age14_composite_r2 - age14_confounders_r2


age14_partial  = rbind(age14_ed_partial, age14_income_partial, age14_wealth_partial, age14_occupation_partial, age14_imd_partial,age14_composite_partial)

age14_partial = as.data.frame(age14_partial)

age14_partial = age14_partial %>%  add_column(indicator= c("Parent Education", "Income", "Wealth", "Occupation", "Relative Neighbourhood Deprivation", "SEP composite"), .before = 1)

age14_partialr2= age14_partial[,1:2]


```

#now put r2 data into flextable!

```{r}
#define border
my_border = border= fp_border(color="black", width=1)

partial_r2_flex<- age14_partialr2 %>% 
  flextable() %>% 
  #add_header_row(top = TRUE, values = "Partial R2 (%)", colwidths = 5) %>% 
  font(fontname = "Times New Roman", part="all") %>% 
  fontsize(size=12, part = "all") %>% 
  align(j=1, align="left", part="all") %>% 
  align(j=2, align="center", part="all") %>% 
  color(j=1:2, color="black", part="all") %>% 
  width(j=1, width=2.2) %>% 
  width(j=2, width=1) %>% 
  line_spacing(j=2, space=1.5) %>% 
  border_remove() %>% 
  hline_top(j=1:2, part="all", border=my_border) %>% 
  hline_bottom(j=1:2,part="body",  border=my_border) %>% 
  set_header_labels(indicator= "Indicator", age14="Age 14") %>% 
 print( preview = "docx") 
```


model comparisons 
```{r}
#age 14
#model with all SES predictors included 
age14_all_predictors<- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home + highest_NVQ +income_quintiles+wealth_quintiles+occupational_status+imd, weights = mcs2_weight))
#model removing each predictor in turn 
age14_no_nvq<- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home + income_quintiles+wealth_quintiles+occupational_status+imd, weights = mcs2_weight))
age14_no_income<- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home + highest_NVQ +wealth_quintiles+occupational_status+imd, weights = mcs2_weight))
age14_no_wealth<- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home + highest_NVQ +income_quintiles+occupational_status+imd, weights = mcs2_weight))
age14_no_occupation<- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home + highest_NVQ +income_quintiles+wealth_quintiles+imd, weights = mcs2_weight))
age14_no_imd<- with(imputed_mcs2, lm(age14_standardised ~   gender +ethnicity +language_used_at_home + highest_NVQ +income_quintiles+wealth_quintiles+occupational_status, weights = mcs2_weight))
D1(age14_all_predictors, age14_no_nvq )
D1(age14_all_predictors, age14_no_income )
D1(age14_all_predictors, age14_no_wealth)
D1(age14_all_predictors, age14_no_occupation )
D1(age14_all_predictors, age14_no_imd)
```

